### ISSUE TITLE
Cloudflare Pages Deploy

### ISSUE THREAD

**Issue by manstfu** [SimeonGriggs/sanity-remix-template#39]
Can you provide more information about how to deploy to cloudflare pages?

Also this information is not very clear, if you transfer your /app folder over, you will lose package.lock,
```
cd ..
# create a new project, and pick a pre-configured host
npx create-remix@latest
cd my-new-remix-app
# remove the new project's app (not the old one!)
rm -rf app
# copy your app over
cp -R ../my-old-remix-app/app app
```

Current error:
```
Error: Failed to publish your Function. Got error: Uncaught ReferenceError: process is not defined
at functionsWorker-0.9622555224340603.js:114556:100 in Wc
at functionsWorker-0.9622555224340603.js:114560:40
```

**Comment by SimeonGriggs** [comment]
You'd be best looking to the Remix documentation and community for moving a Remix Node project over the Cloudflare pages.
